### ISSUE TITLE
[BUG] Malfunctioning/confusing/redundant Index template method

### ISSUE THREAD

**Issue by wbeckler** [opensearch-project/opensearch-go#151]
The Go client contains two methods for using index templates. One of them, `opensearchapi.IndicesPutTemplateRequest,` uses a nonexistent legacy REST API (`/_template`). 

In OpenSearch v1.x and v2.x the correct REST API is `/_index_template`, which is accessible by the correct method `opensearchapi.IndicesPutIndexTemplateRequest`.

I would propose we remove the legacy method, which is confusing and points to an unsupported API.

**Comment by dblock** [comment]
Deprecate the method in a minor release and remove in major.

**Comment by wbeckler** [comment]
Would we consider this to be a "breaking" change rather than a bugfix if the method points to a nonexistent API in OpenSearch?

**Comment by dblock** [comment]
So the method never worked (aka produced an error)? If so removing it is fine as a bugfix.

**Comment by Jakob3xD** [comment]
FYI: The `_template` still exists and is also working in Opensearch 2.6.0.
Therefore it is deprecated but still a valid way to do templating.

**Comment by whym9** [comment]
If this issue is still relevant, I would like to solve it.

**Comment by Jakob3xD** [comment]
@whym9 how is this issue affecting you?


As already mentioned both APIs still exist and both work. I personally don´t see this as a bug. IMO we should add some sort of deprecation warning/comment to the request type linking/referring to the request type for the `_index_template` api. We should remove this once the API get removed from Opensearch it self. Otherwise we reduce the Opensearch api support.
WDYT @wbeckler

**Comment by tannerjones4075** [comment]
If this issue is still relevant, I would like to solve it.

**Comment by VachaShah** [comment]
Thank you @tannerjones4075! Assigning this to you.

**Comment by tannerjones4075** [comment]
This issue can be closed because the issue has been resolved: https://github.com/opensearch-project/opensearch-go/pull/390
