### ISSUE TITLE
[FEATURE] Support for upsert in BulkIndexer Update action

### ISSUE THREAD

**Issue by SaiSatwik** [opensearch-project/opensearch-go#207]
### Is your feature request related to a problem?
In openserch Go client, 'update' action on BulkIndexerItem is not supporting 'upsert' flag currently. 'upsert' flag is used.
Upsert is used to insert a new document into a database if it does not exist, or updates an existing document if it does exist.
May be support for the flag can be provided in BulkIndexerItem type
https://github.com/opensearch-project/opensearch-go/blob/v1.1.0/opensearchutil/bulk_indexer.go#L111

### What solution would you like?
Support for 'upsert' flag in BulkIndexerItem type in opensearch go client library.

### What alternatives have you considered?
As of now, we use index operation for update as well so if document doesn't exist it will create a new document.

### Do you have any additional context?
No

**Comment by arunx2** [comment]
It would be a needed addition to the API.

**Comment by zethuman** [comment]
AFAIK, all bulk requests in either are combined into one interface where requests will be sent. That is, a create, delete, update request is sent in the same format. I would like to discuss with the community in which version should be refactor? 
* If add some tag, will it not turn out to be an overweight for the rest of the operations? 
* If add a new abstract parameter where you can pass additional parameters? (this option suits me better)

**Comment by zethuman** [comment]
@SaiSatwik, I decided to dig deeper into this issue and started digging into the source code. So, my previous post was wrong, as the source code already supports this functionality. However, it would seem non-obvious, on the other hand it gives a lot of flexibility in terms of use. In order to show how to use it, I decided to slightly tweak the integration test cases #269 . Please review and provide feedback. If this solves your problem, please close the issue.

**Comment by dblock** [comment]
I merged #269, thanks!
